version: '3'
services:
  logstack-api:
    image: aceleradev/logstack-api
    network_mode: bridge
    container_name: logstack-api
    environment:
      - DB_HOST=logstack-db
      - DB_HOST_PORT=5432
      - DB_NAME=logstack
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - logstack-db
    links:
      - logstack-db
  logstack-db:
    image: postgres:10.4
    network_mode: bridge
    container_name: logstack-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=logstack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
volumes:
  postgres-data: